manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmk
      revision: v3.5.0
      import: app/west.yml

  self:
    path: config
