manifest:
  remotes:
    - name: imdanielbui
      url-base: https://github.com/imdanielbui

  projects:
    - name: zmk
      remote: imdanielbui
      revision: main
      import: app/west.yml

  self:
    path: config
